import React, { useState } from 'react';
import { FileText, Sparkles, Download, Share2, Calendar, Loader2 } from 'lucide-react';
import { generateMonthlyReport } from '../../utils/insights/reporting';

import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';
import { Transaction, MonthlyStats } from '../../types';

interface ReportsViewProps {
  transactions: Transaction[];
  currency: string;
  monthlyStats: MonthlyStats;
}

export default function ReportsView({ transactions, currency, monthlyStats }: ReportsViewProps) {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  
  const currentMonth = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await generateMonthlyReport(currentMonth, transactions);
      setReport(res);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SpendWise-Report-${currentMonth.replace(' ', '-')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="view-enter max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black text-[var(--text-primary)] flex items-center gap-3">
            <FileText size={28} className="text-[var(--teal)]" />
            Financial Intelligence
          </h2>
          <p className="text-[var(--text-muted)] font-medium mt-1">Deep insights generated by SpendWise Local AI.</p>
        </div>
        
        <button 
          onClick={handleGenerate}
          disabled={loading}
          className="flex items-center gap-2 px-6 py-3 bg-[var(--teal)] text-white border-none rounded-2xl cursor-pointer font-bold shadow-lg shadow-teal-500/20 hover:scale-105 active:scale-95 transition-all disabled:opacity-50"
        >
          {loading ? <Loader2 className="animate-spin" size={18} /> : <Sparkles size={18} />}
          {report ? 'REGENERATE REPORT' : 'GENERATE MONTHLY REPORT'}
        </button>
      </div>

      {!report && !loading && (
        <div className="bg-[var(--surface-card)] rounded-[40px] p-12 border border-[var(--border)] text-center space-y-4">
          <div className="w-20 h-20 bg-[var(--surface-input)] rounded-full flex items-center justify-center mx-auto mb-6">
            <Calendar size={32} className="text-[var(--text-muted)]" />
          </div>
          <h3 className="text-xl font-bold text-[var(--text-primary)]">Your {currentMonth} Report is Ready</h3>
          <p className="text-[var(--text-muted)] max-w-md mx-auto">
            Get a witty, AI-powered analysis of your spending patterns, savings rate, and actionable tips to optimize your finances using SpendWise Local AI.
          </p>
        </div>
      )}

      {loading && (
        <div className="bg-[var(--surface-card)] rounded-[40px] p-20 border border-[var(--border)] text-center">
          <div className="flex flex-col items-center gap-4">
            <div className="relative">
              <div className="w-16 h-16 border-4 border-[var(--teal)]/20 border-t-[var(--teal)] rounded-full animate-spin" />
              <Sparkles className="absolute inset-0 m-auto text-[var(--teal)] animate-pulse" size={24} />
            </div>
            <p className="font-bold text-[var(--text-primary)] animate-pulse">Local AI is decoding your behavioral patterns...</p>
          </div>
        </div>
      )}

      {report && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-[var(--surface-card)] rounded-[40px] border border-[var(--border)] shadow-xl overflow-hidden"
        >
          <div className="px-8 py-6 bg-gradient-to-r from-[var(--teal)]/10 to-transparent border-b border-[var(--border)] flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-[var(--teal)] flex items-center justify-center text-white">
                <Sparkles size={20} />
              </div>
              <div>
                <h4 className="font-bold text-[var(--text-primary)]">AI Monthly Insights</h4>
                <span className="text-[10px] text-[var(--text-muted)]">Powered by SpendWise Local AI</span>
              </div>
            </div>
            <div className="flex gap-2">
              <button 
                onClick={handleDownload}
                className="p-2.5 bg-[var(--surface-input)] text-[var(--text-primary)] rounded-xl border-none cursor-pointer hover:bg-[var(--border)] transition-colors"
                title="Download as Markdown"
              >
                <Download size={18} />
              </button>
              <button className="p-2.5 bg-[var(--surface-input)] text-[var(--text-primary)] rounded-xl border-none cursor-pointer hover:bg-[var(--border)] transition-colors">
                <Share2 size={18} />
              </button>
            </div>
          </div>
          
          <div className="p-8 prose prose-slate max-w-none prose-p:text-[var(--text-primary)] prose-headings:text-[var(--text-primary)] prose-strong:text-[var(--teal)] prose-li:text-[var(--text-primary)]">
            <ReactMarkdown>{report}</ReactMarkdown>
          </div>
        </motion.div>
      )}
    </div>
  );
}
