import React, { useRef, useState } from 'react';
import { FileText, Sparkles, Download, Share2, Calendar, Loader2, Printer } from 'lucide-react';
import { generateMonthlyReport } from '../../utils/insights/reporting';

import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';
import { Transaction, MonthlyStats } from '../../types';

interface ReportsViewProps {
  transactions: Transaction[];
  currency: string;
  monthlyStats: MonthlyStats;
}

export default function ReportsView({ transactions, currency, monthlyStats }: ReportsViewProps) {
  const [report, setReport] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const currentMonth = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await generateMonthlyReport(currentMonth, transactions);
      setReport(res);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadMD = () => {
    if (!report) return;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `SpendWise-Report-${currentMonth.replace(' ', '-')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrintPDF = () => {
    if (!report || !printRef.current) return;
    const printWindow = window.open('', '_blank', 'width=900,height=700');
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>SpendWise Report — ${currentMonth}</title>
        <style>
          body { font-family: 'Georgia', serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1a1a2e; line-height: 1.7; }
          h1, h2, h3 { color: #0f766e; }
          h1 { font-size: 2rem; border-bottom: 3px solid #0f766e; padding-bottom: 8px; }
          h2 { font-size: 1.4rem; margin-top: 32px; }
          h3 { font-size: 1.1rem; }
          p { margin: 12px 0; }
          ul, ol { padding-left: 24px; }
          li { margin: 6px 0; }
          strong { color: #0f766e; }
          .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 1px solid #e5e7eb; }
          .badge { background: #0f766e; color: white; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: bold; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 style="border:none;margin:0;">💰 SpendWise</h1>
            <p style="margin:4px 0;color:#6b7280;font-size:14px;">Financial Intelligence Report</p>
          </div>
          <span class="badge">${currentMonth}</span>
        </div>
        ${printRef.current.innerHTML}
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => { printWindow.print(); }, 500);
  };

  const handleShare = async () => {
    if (!report) return;
    if (navigator.share) {
      await navigator.share({ title: `SpendWise Report — ${currentMonth}`, text: report });
    } else {
      await navigator.clipboard.writeText(report);
      alert('Report copied to clipboard!');
    }
  };

  return (
    <div className="view-enter max-w-4xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-3xl font-black text-[var(--text-primary)] flex items-center gap-3">
            <FileText size={28} className="text-[var(--teal)]" />
            Financial Intelligence
          </h2>
          <p className="text-[var(--text-muted)] font-medium mt-1">Deep insights generated by SpendWise Local AI.</p>
        </div>
        
        <button 
          onClick={handleGenerate}
          disabled={loading}
          className="flex items-center gap-2 px-6 py-3 bg-[var(--teal)] text-white border-none rounded-2xl cursor-pointer font-bold shadow-lg shadow-teal-500/20 hover:scale-105 active:scale-95 transition-all disabled:opacity-50"
        >
          {loading ? <Loader2 className="animate-spin" size={18} /> : <Sparkles size={18} />}
          {report ? 'REGENERATE REPORT' : 'GENERATE MONTHLY REPORT'}
        </button>
      </div>

      {!report && !loading && (
        <div className="bg-[var(--surface-card)] rounded-[40px] p-12 border border-[var(--border)] text-center space-y-4">
          <div className="w-20 h-20 bg-[var(--surface-input)] rounded-full flex items-center justify-center mx-auto mb-6">
            <Calendar size={32} className="text-[var(--text-muted)]" />
          </div>
          <h3 className="text-xl font-bold text-[var(--text-primary)]">Your {currentMonth} Report is Ready</h3>
          <p className="text-[var(--text-muted)] max-w-md mx-auto">
            Get a witty, AI-powered analysis of your spending patterns, savings rate, and actionable tips to optimize your finances using SpendWise Local AI.
          </p>
        </div>
      )}

      {loading && (
        <div className="bg-[var(--surface-card)] rounded-[40px] p-20 border border-[var(--border)] text-center">
          <div className="flex flex-col items-center gap-4">
            <div className="relative">
              <div className="w-16 h-16 border-4 border-[var(--teal)]/20 border-t-[var(--teal)] rounded-full animate-spin" />
              <Sparkles className="absolute inset-0 m-auto text-[var(--teal)] animate-pulse" size={24} />
            </div>
            <p className="font-bold text-[var(--text-primary)] animate-pulse">Local AI is decoding your behavioral patterns...</p>
          </div>
        </div>
      )}

      {report && (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-[var(--surface-card)] rounded-[40px] border border-[var(--border)] shadow-xl overflow-hidden"
        >
          <div className="px-8 py-6 bg-gradient-to-r from-[var(--teal)]/10 to-transparent border-b border-[var(--border)] flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-[var(--teal)] flex items-center justify-center text-white">
                <Sparkles size={20} />
              </div>
              <div>
                <h4 className="font-bold text-[var(--text-primary)]">AI Monthly Insights</h4>
                <span className="text-[10px] text-[var(--text-muted)]">Powered by SpendWise Local AI</span>
              </div>
            </div>
            <div className="flex gap-2">
              <button 
                onClick={handleDownloadMD}
                className="p-2.5 bg-[var(--surface-input)] text-[var(--text-primary)] rounded-xl border-none cursor-pointer hover:bg-[var(--border)] transition-colors"
                title="Download as Markdown"
                aria-label="Download report as Markdown"
              >
                <Download size={18} />
              </button>
              <button 
                onClick={handlePrintPDF}
                className="flex items-center gap-1.5 px-3 py-2 bg-[var(--teal-dim)] text-[var(--teal)] rounded-xl border-none cursor-pointer hover:opacity-80 transition-colors text-xs font-bold"
                title="Export as PDF"
                aria-label="Export report as PDF"
              >
                <Printer size={15} /> PDF
              </button>
              <button 
                onClick={handleShare}
                className="p-2.5 bg-[var(--surface-input)] text-[var(--text-primary)] rounded-xl border-none cursor-pointer hover:bg-[var(--border)] transition-colors"
                title="Share Report"
                aria-label="Share report"
              >
                <Share2 size={18} />
              </button>
            </div>
          </div>
          
          <div ref={printRef} className="p-8 prose prose-slate max-w-none prose-p:text-[var(--text-primary)] prose-headings:text-[var(--text-primary)] prose-strong:text-[var(--teal)] prose-li:text-[var(--text-primary)]">
            <ReactMarkdown>{report}</ReactMarkdown>
          </div>
        </motion.div>
      )}
    </div>
  );
}
